# This workflow will build and test a Go project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23" # Use a version that satisfies the linter's requirements
          check-latest: true # check if a newer version is available

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Lint
        run: staticcheck ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Test with Coverage
        run: |
          go test -v -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out > coverage-summary.txt

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-test-results
          path: |
            coverage.out
            coverage-summary.txt
        if: always() # Ensure artifacts are uploaded even if tests fail, to inspect results

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: demoulin/countrycontinent
